### ISSUE TITLE
make mindmaps 32bit compatible?

### ISSUE THREAD

**Issue by aseedorf** [splitt3r/mindmaps#36]
we use nextcloud on a raspberry pi 3,
all apps are working, but mindmaps needs 64bit to enable it.
is it possible, to run it on a raspberry pi3?

**Comment by splitt3r** [comment]
Hi, I'm [GitMate.io](https://gitmate.io)!

It seems you've just enabled the issue triaging. I'm just scraping all issues from your repository and will give you some more information about this in a few minutes or so.

Because of the rate limit we can't scrape all information (including all comments and authors) right now - our system is already set up to scrape this in the next days over which the predictions will become more precise every day.

If you want me to use a different account for triaging your issues, simply create one and log in with it.

**Sit tight!**

**Comment by splitt3r** [comment]
Will drop that dependency. It was copied from an official example.
